openapi: 3.0.3
servers:
- url: http://localhost:5085/
  description: url Local
- url: https://dev.nttdata.com/msinformation/
  description: url Desarrollo
- url: https://nttdata.com/msinformation/
  description: url Produccion